name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Generate sitemap
      run: npm run generate-sitemap

    - name: Create robots.txt file
      run: |
        echo 'User-agent: *' > ./dist/robots.txt
        echo 'Disallow:' >> ./dist/robots.txt
        echo 'Sitemap: https://striker-base.com/sitemap.xml' >> ./dist/robots.txt

    - name: Add CNAME file
      run: echo 'striker-base.com' > ./dist/CNAME

    - name: Create 404.html file
      run: |
        echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/index.html" /></head><body><script>window.location.href="/index.html?path=" + encodeURIComponent(window.location.pathname + window.location.search + window.location.hash);</script></body></html>' > ./dist/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
